# Generated by Django 5.1.1 on 2024-10-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='article',
            new_name='articulo',
        ),
    ]
